apiVersion: apps/v1
kind: Deployment

metadata:
  name: ${APP_NAME}
  labels:
    app: ${APP_NAME}

spec:
  replicas: 2

  selector:
    matchLabels:
      app: ${APP_NAME}

  template:
    metadata:
      labels:
        app: ${APP_NAME}

    spec:
      automountServiceAccountToken: false

      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        seccompProfile:
          type: RuntimeDefault

      containers:
        - name: ${APP_NAME}
          image: ${IMAGE_NAME}
          imagePullPolicy: Never

          securityContext:
            allowPrivilegeEscalation: false
            privileged: false
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL

          ports:
            - containerPort: 8000

          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10

          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 20