apiVersion: apps/v1
kind: Deployment
metadata:
  name: finacplus-api
  labels:
    app: finacplus-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: finacplus-api
  template:
    metadata:
      labels:
        app: finacplus-api
    spec:
      containers:
        - name: finacplus-api
          image: finacplus-api:local
          imagePullPolicy: Never
          ports:
            - containerPort: 8000
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 20